spring:
  application:
    name: myportefolio

  spring:
    datasource:
      url: jdbc:sqlite:/tmp/myportefolio.db
      driver-class-name: org.sqlite.JDBC
      # Configuration importante pour SQLite
      hikari:
        maximum-pool-size: 1

    jpa:
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        ddl-auto: none  # Désactive la création automatique des tables
      properties:
        hibernate:
          dialect: org.hibernate.community.dialect.SQLiteDialect
          format_sql: true
          # Configuration spécifique pour SQLite
          connection:
            handling_mode: DELAYED_ACQUISITION_AND_HOLD
      show-sql: true

    # Désactive l'initialisation automatique du schéma
    sql:
      init:
        mode: never





# Variables d'environnement pour le développement
frontend_url: {FRONTEND_URL}


# Configuration des logs
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        web.cors: TRACE