spring:
  application:
    name: myportefolio

  # Configuration de la base de donn\u00E9es PostgreSQL
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # Configuration JPA et Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  # Configuration CORS
  web:
    cors:
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-origins: ${ALLOWED_ORIGINS}
      allow-credentials: true

    # Configuration pour lee front end url

application:
    frontend_url: https://nilswenting.com


server:
  port: ${PORT:8080}