spring:
  application:
    name: myportefolio

  spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

  datasource:
    url: jdbc:sqlite:portfolio.db
    driver-class-name: org.sqlite.JDBC





# Variables d'environnement pour le développement
frontend_url: {FRONTEND_URL}


# Configuration des logs
logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        web.cors: TRACE